"""initial schema

Revision ID: fd1b56b5db58
Revises:
Create Date: 2026-05-19 21:15:53.425855
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd1b56b5db58"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_history_entries",
        sa.Column("set_number", sa.String(length=20), nullable=False),
        sa.Column("set_name", sa.String(length=300), nullable=False),
        sa.Column("release_year", sa.Integer(), nullable=False),
        sa.Column("theme", sa.String(length=100), nullable=False),
        sa.Column("set_age", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("uvp", sa.Float(), nullable=True),
        sa.Column("offer_price", sa.Float(), nullable=False),
        sa.Column("discount_vs_uvp", sa.Float(), nullable=True),
        sa.Column("market_price", sa.Float(), nullable=False),
        sa.Column("num_sources", sa.Integer(), nullable=False),
        sa.Column("roi_percent", sa.Float(), nullable=False),
        sa.Column("annualized_roi", sa.Float(), nullable=False),
        sa.Column("net_profit", sa.Float(), nullable=False),
        sa.Column("total_purchase_cost", sa.Float(), nullable=False),
        sa.Column("total_selling_costs", sa.Float(), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("risk_rating", sa.String(length=50), nullable=False),
        sa.Column("recommendation", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("suggestions", sa.JSON(), nullable=False),
        sa.Column("opportunity_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("source_prices", sa.JSON(), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_platform", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_history_entries_analyzed_at"), "analysis_history_entries", ["analyzed_at"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_history_entries_set_number"), "analysis_history_entries", ["set_number"], unique=False
    )
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("is_secret", sa.Boolean(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "inventory_items",
        sa.Column("set_number", sa.String(length=20), nullable=False),
        sa.Column("set_name", sa.String(length=300), nullable=False),
        sa.Column("theme", sa.String(length=100), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("buy_price", sa.Float(), nullable=False),
        sa.Column("buy_shipping", sa.Float(), nullable=False),
        sa.Column("buy_date", sa.Date(), nullable=False),
        sa.Column("buy_platform", sa.String(length=100), nullable=True),
        sa.Column("buy_url", sa.Text(), nullable=True),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("current_market_price", sa.Float(), nullable=True),
        sa.Column("market_price_updated_at", sa.DateTime(), nullable=True),
        sa.Column("unrealized_profit", sa.Float(), nullable=True),
        sa.Column("unrealized_roi_percent", sa.Float(), nullable=True),
        sa.Column("sell_signal_active", sa.Boolean(), nullable=False),
        sa.Column("sell_signal_reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sell_price", sa.Float(), nullable=True),
        sa.Column("sell_date", sa.Date(), nullable=True),
        sa.Column("sell_platform", sa.String(length=100), nullable=True),
        sa.Column("realized_profit", sa.Float(), nullable=True),
        sa.Column("realized_roi_percent", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_inventory_set_number", "inventory_items", ["set_number"], unique=False)
    op.create_index("ix_inventory_status", "inventory_items", ["status"], unique=False)
    op.create_table(
        "lego_sets",
        sa.Column("set_number", sa.String(length=20), nullable=False),
        sa.Column("set_name", sa.String(length=300), nullable=False),
        sa.Column("theme", sa.String(length=100), nullable=False),
        sa.Column("subtheme", sa.String(length=100), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=False),
        sa.Column("piece_count", sa.Integer(), nullable=True),
        sa.Column("minifigure_count", sa.Integer(), nullable=True),
        sa.Column("uvp_eur", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("box_dimensions", sa.String(length=50), nullable=True),
        sa.Column("eol_status", sa.String(length=20), nullable=False),
        sa.Column("eol_date", sa.Date(), nullable=True),
        sa.Column("is_exclusive", sa.Boolean(), nullable=False),
        sa.Column("is_gwp", sa.Boolean(), nullable=False),
        sa.Column("theme_tier", sa.String(length=10), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=True),
        sa.Column("current_market_price", sa.Float(), nullable=True),
        sa.Column("market_price_updated_at", sa.DateTime(), nullable=True),
        sa.Column("growth_percent", sa.Float(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("brickeconomy_url", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("set_number"),
    )
    op.create_index("ix_lego_sets_eol_status", "lego_sets", ["eol_status"], unique=False)
    op.create_index("ix_lego_sets_set_number", "lego_sets", ["set_number"], unique=True)
    op.create_index("ix_lego_sets_theme", "lego_sets", ["theme"], unique=False)
    op.create_index("ix_lego_sets_year", "lego_sets", ["release_year"], unique=False)
    op.create_table(
        "auction_watch_items",
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("source_platform", sa.String(length=30), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("lot_title", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("current_bid", sa.Float(), nullable=False),
        sa.Column("purchase_shipping", sa.Float(), nullable=False),
        sa.Column("desired_roi_percent", sa.Float(), nullable=True),
        sa.Column("buyer_fee_rate", sa.Float(), nullable=True),
        sa.Column("buyer_fee_fixed", sa.Float(), nullable=True),
        sa.Column("fee_applies_to_shipping", sa.Boolean(), nullable=False),
        sa.Column("max_bid", sa.Float(), nullable=True),
        sa.Column("break_even_bid", sa.Float(), nullable=True),
        sa.Column("bid_gap", sa.Float(), nullable=True),
        sa.Column("expected_roi_current", sa.Float(), nullable=True),
        sa.Column("expected_roi_target", sa.Float(), nullable=True),
        sa.Column("expected_profit_current", sa.Float(), nullable=True),
        sa.Column("expected_profit_target", sa.Float(), nullable=True),
        sa.Column("all_in_cost_current", sa.Float(), nullable=True),
        sa.Column("all_in_cost_target", sa.Float(), nullable=True),
        sa.Column("buyer_fee_current", sa.Float(), nullable=True),
        sa.Column("buyer_fee_target", sa.Float(), nullable=True),
        sa.Column("market_price", sa.Float(), nullable=True),
        sa.Column("reference_price", sa.Float(), nullable=True),
        sa.Column("reference_label", sa.String(length=40), nullable=True),
        sa.Column("set_category", sa.String(length=20), nullable=True),
        sa.Column("eol_status", sa.String(length=20), nullable=True),
        sa.Column("bid_status", sa.String(length=20), nullable=True),
        sa.Column("recommendation_text", sa.Text(), nullable=True),
        sa.Column("warning_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_alerted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("check_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["set_id"], ["lego_sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_auction_watch_active", "auction_watch_items", ["is_active"], unique=False)
    op.create_index("ix_auction_watch_last_checked", "auction_watch_items", ["last_checked_at"], unique=False)
    op.create_index("ix_auction_watch_platform", "auction_watch_items", ["source_platform"], unique=False)
    op.create_index("ix_auction_watch_status", "auction_watch_items", ["status"], unique=False)
    op.create_table(
        "inventory_photos",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["item_id"], ["inventory_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inventory_photos_item_id"), "inventory_photos", ["item_id"], unique=False)
    op.create_table(
        "offers",
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("offer_url", sa.Text(), nullable=False),
        sa.Column("offer_title", sa.String(length=500), nullable=False),
        sa.Column("price_eur", sa.Float(), nullable=False),
        sa.Column("shipping_eur", sa.Float(), nullable=True),
        sa.Column("total_price_eur", sa.Float(), nullable=True),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("box_damage", sa.Boolean(), nullable=False),
        sa.Column("sealed", sa.Boolean(), nullable=False),
        sa.Column("seller_name", sa.String(length=200), nullable=True),
        sa.Column("seller_rating", sa.Float(), nullable=True),
        sa.Column("seller_location", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_auction", sa.Boolean(), nullable=False),
        sa.Column("auction_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_roi", sa.Float(), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("recommendation", sa.String(length=20), nullable=True),
        sa.Column("analysis_notes", sa.Text(), nullable=True),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["set_id"], ["lego_sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_offers_discovered", "offers", ["discovered_at"], unique=False)
    op.create_index("ix_offers_set_platform", "offers", ["set_id", "platform"], unique=False)
    op.create_index("ix_offers_status", "offers", ["status"], unique=False)
    op.create_table(
        "price_records",
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("price_eur", sa.Float(), nullable=False),
        sa.Column("price_original", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("sold_count", sa.Integer(), nullable=True),
        sa.Column("median_price", sa.Float(), nullable=True),
        sa.Column("min_price", sa.Float(), nullable=True),
        sa.Column("max_price", sa.Float(), nullable=True),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("is_reliable", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["set_id"], ["lego_sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_price_records_scraped_at", "price_records", ["scraped_at"], unique=False)
    op.create_index("ix_price_records_set_source", "price_records", ["set_id", "source"], unique=False)
    op.create_table(
        "watchlist_items",
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("target_price", sa.Float(), nullable=True),
        sa.Column("min_roi", sa.Float(), nullable=True),
        sa.Column("max_risk", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["set_id"], ["lego_sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deal_feedback",
        sa.Column("set_id", sa.Integer(), nullable=False),
        sa.Column("offer_id", sa.Integer(), nullable=True),
        sa.Column("purchase_price", sa.Float(), nullable=False),
        sa.Column("purchase_shipping", sa.Float(), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("purchase_platform", sa.String(length=20), nullable=False),
        sa.Column("sale_price", sa.Float(), nullable=True),
        sa.Column("sale_fees", sa.Float(), nullable=True),
        sa.Column("sale_shipping", sa.Float(), nullable=True),
        sa.Column("sale_packaging", sa.Float(), nullable=True),
        sa.Column("sale_date", sa.Date(), nullable=True),
        sa.Column("sale_platform", sa.String(length=20), nullable=True),
        sa.Column("actual_profit", sa.Float(), nullable=True),
        sa.Column("actual_roi", sa.Float(), nullable=True),
        sa.Column("holding_months", sa.Float(), nullable=True),
        sa.Column("annualized_roi", sa.Float(), nullable=True),
        sa.Column("predicted_roi", sa.Float(), nullable=True),
        sa.Column("roi_deviation", sa.Float(), nullable=True),
        sa.Column("predicted_risk_score", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("difficulty", sa.String(length=20), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["offer_id"], ["offers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["set_id"], ["lego_sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deal_feedback")
    op.drop_table("watchlist_items")
    op.drop_index("ix_price_records_set_source", table_name="price_records")
    op.drop_index("ix_price_records_scraped_at", table_name="price_records")
    op.drop_table("price_records")
    op.drop_index("ix_offers_status", table_name="offers")
    op.drop_index("ix_offers_set_platform", table_name="offers")
    op.drop_index("ix_offers_discovered", table_name="offers")
    op.drop_table("offers")
    op.drop_index(op.f("ix_inventory_photos_item_id"), table_name="inventory_photos")
    op.drop_table("inventory_photos")
    op.drop_index("ix_auction_watch_status", table_name="auction_watch_items")
    op.drop_index("ix_auction_watch_platform", table_name="auction_watch_items")
    op.drop_index("ix_auction_watch_last_checked", table_name="auction_watch_items")
    op.drop_index("ix_auction_watch_active", table_name="auction_watch_items")
    op.drop_table("auction_watch_items")
    op.drop_index("ix_lego_sets_year", table_name="lego_sets")
    op.drop_index("ix_lego_sets_theme", table_name="lego_sets")
    op.drop_index("ix_lego_sets_set_number", table_name="lego_sets")
    op.drop_index("ix_lego_sets_eol_status", table_name="lego_sets")
    op.drop_table("lego_sets")
    op.drop_index("ix_inventory_status", table_name="inventory_items")
    op.drop_index("ix_inventory_set_number", table_name="inventory_items")
    op.drop_table("inventory_items")
    op.drop_table("app_settings")
    op.drop_index(op.f("ix_analysis_history_entries_set_number"), table_name="analysis_history_entries")
    op.drop_index(op.f("ix_analysis_history_entries_analyzed_at"), table_name="analysis_history_entries")
    op.drop_table("analysis_history_entries")
    # ### end Alembic commands ###
